#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
fail() { echo "earth_ground_lighting_contract_test: FAIL: $*" >&2; exit 1; }
has() { rg -qF "$1" "$2" || fail "$3"; }

shader="$ROOT/assets/shaders/earth_ground.gdshader"
controller="$ROOT/scripts/EarthGroundController.cs"
launch_shader="$ROOT/assets/shaders/launch_surface.gdshader"
launch_pad="$ROOT/scripts/LaunchPadController.cs"
far_field="$ROOT/scripts/StarbaseFarField.cs"
surface="$ROOT/assets/shaders/earth_surface.gdshader"
origin="$ROOT/scripts/FloatingOrigin.cs"
lighting="$ROOT/scripts/PhaseLightingController.cs"

[[ -f "$launch_shader" ]] || fail "launch surface shader is missing"
has 'v_world_position = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz' "$launch_shader" "launch surface detail is not world-space stable"
has 'float aggregate = noise01' "$launch_shader" "launch surface has no aggregate breakup"
has 'float grain = noise01' "$launch_shader" "launch surface has no fine grain"
has 'CreateLaunchSurfaceMaterial' "$launch_pad" "launch pad does not bind procedural surface materials"
has 'ApplySurface("OrbitalPadApron"' "$launch_pad" "starbase apron is not textured"

has 'uniform float night_floor' "$shader" "Earth ground has no bounded indirect night floor"
has 'uniform sampler2D night_tex' "$shader" "Earth ground has no real night-side texture input"
has 'uniform float terrain_relief_strength' "$shader" "Earth ground has no bounded local relief control"
has 'v_patch        = VERTEX.xz * metres_per_unit;' "$shader" "Earth ground detail coordinate depends on unreliable UV2 interpolation"
has 'float macro = noise01' "$shader" "Earth ground has no multi-scale macro terrain breakup"
has 'float regional = noise01' "$shader" "Earth ground has no regional terrain breakup"
has 'float relief_scale = terrain_relief_strength * land_mask' "$shader" "Earth ground relief is not restricted to land"
has 'vec3 city_lights = night_map * city_mask * night_side' "$shader" "Earth ground city lights do not follow the night side"
has 'uniform float terminator_width' "$shader" "Earth ground has no bounded terminator transition"
has 'float terminator = smoothstep' "$shader" "Earth ground terminator transition is not explicit"
has 'vec3 direct = vec3(1.05 * ndl * solar_visibility)' "$shader" "Earth ground direct solar term is not visibility-gated"
has 'render_mode cull_back, unshaded, depth_draw_opaque' "$shader" "Earth ground must own its manual radiance on the opaque pass"
has 'earthshine_gain' "$shader" "Earth ground earthshine gain is missing"
has 'earthshine_min_reflectance' "$shader" "Earth ground minimum earthshine reflectance is missing"
has 'ground_radiance = lit + indirect_emission + city_lights' "$shader" "Earth ground earthshine is not composed into radiance"
has 'night_floor", NightFloor' "$controller" "Earth ground calibration is not configured from C#"
has 'private const float NightFloor = 0.12f;' "$controller" "Earth ground floor is not at the validated bounded ceiling"
has 'private const float EarthshineGain = 2.80f;' "$controller" "Earth ground earthshine gain is not configured"
has 'private const float EarthshineMinReflectance = 0.055f;' "$controller" "Earth ground minimum reflectance is not configured"
has 'private const float DetailStrength = 0.18f;' "$controller" "Earth ground detail strength is not configured"
has 'private const float TerrainReliefStrength = 0.18f;' "$controller" "Earth ground relief strength is not configured"
has 'private const float NightCityGain = 0.34f;' "$controller" "Earth ground city-light gain is not configured"
has 'earth_night.jpg' "$controller" "Earth ground does not bind the night texture"
has 'private const float CoastalGrade = 0.28f;' "$controller" "Earth ground coastal grade is not configured"
has 'private const float HorizonHazeStrength = 0.92f;' "$controller" "Earth ground horizon haze is too broad or unconfigured"
has 'HorizonHazeStrength' "$controller" "Earth ground horizon seam mitigation is not bounded/configured"

has 'GetSurfacePoint(vessel.Position, 0.0)' "$controller" "Earth ground is not anchored to the live ellipsoid surface"
has 'GetGeodeticUp(vessel.Position)' "$controller" "Earth ground does not use geodetic up"
has 'EarthGlobeAlpha' "$controller" "Earth ground fade is not complementary with the scaled-space globe"
has 'EarthVisualHandoffLowM = 40_000.0' "$origin" "Earth visual handoff low altitude changed"
has 'EarthVisualHandoffHighM = 75_000.0' "$origin" "Earth visual handoff high altitude changed"
has 'VisualSurfaceRadiusMetres' "$origin" "scaled-space Earth does not read live surface radius"
has 'BuildStarbaseFarField' "$launch_pad" "starbase far-field context is not built"
has 'FloatingOrigin.EarthGlobeAlpha(altitude)' "$far_field" "Starbase far-field is not coupled to the Earth handoff"
has 'CommodityTankMaxHeight' "$far_field" "Starbase far-field tank scale is not sourced from LaunchComplexSpec"
has 'float tankRadius = 4.2f' "$far_field" "Starbase far-field tank radius drifted from the hero farm"
has 'float site_core = 1.0 - smoothstep' "$shader" "Earth ground does not reconstruct land out to the play-camera horizon"
has 'float coastal_belt = 1.0 - smoothstep' "$shader" "Earth ground has no coastal belt beyond the pad island"
if rg -q 'StarbaseWetlandSkirt|StarbaseDuneShoulder|StarbaseCoastalFill' "$launch_pad"; then
  fail "starbase ground cookies are still authored in LaunchPadController"
fi
has 'uniform float edge_fade' "$launch_shader" "launch surface has no skirt edge fade"
has 'edgeFade: 1f' "$launch_pad" "starbase wetland skirt does not fade into the planetary patch"
has 'PatchRadiusUnits = 280_000f' "$controller" "Earth ground disc does not reach the geometric horizon"
has 'FadeCivilGroundBox' "$controller" "civil Ground/wetland cookie is not faded on ascent"
has 'LocalPatchOpacity' "$controller" "Earth ground does not expose compositor opacity"
has 'OrbitalPadApron' "$controller" "orbital pad apron cookie is not faded with the civil ground"
has 'float look_down = smoothstep' "$shader" "Earth ground nadir views still apply grazing haze"
has 'float horizon_m = max(horizon_dist * metres_per_unit' "$shader" "Earth ground rim is not a circular geometric-horizon fade"
has 'PadShadowMaxDistance = 900f' "$lighting" "pad directional shadows do not cover the tower/stack"
has 'RadialSegments = 384' "$origin" "scaled-space Earth globe is still the low-tessellation sawtooth sphere"
has 'float limb_aa = max(fwidth(limb)' "$surface" "Earth limb has no fwidth antialias against the sky"
has 'render_mode cull_back, unshaded, blend_mix' "$surface" "Earth limb ALPHA is ignored without blend_mix"

echo "earth_ground_lighting_contract_test: PASS (bounded night floor, ellipsoid disc, nadir haze gate, limb blend_mix)"
