#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
fail() { echo "earth_ground_lighting_contract_test: FAIL: $*" >&2; exit 1; }
has() { rg -qF "$1" "$2" || fail "$3"; }

shader="$ROOT/assets/shaders/earth_ground.gdshader"
controller="$ROOT/scripts/EarthGroundController.cs"
manifest="$ROOT/data/launch_sites/starbase_terrain.json"
launch_shader="$ROOT/assets/shaders/launch_surface.gdshader"
launch_pad="$ROOT/scripts/LaunchPadController.cs"
far_field="$ROOT/scripts/StarbaseFarField.cs"
surface="$ROOT/assets/shaders/earth_surface.gdshader"
origin="$ROOT/scripts/FloatingOrigin.cs"
lighting="$ROOT/scripts/PhaseLightingController.cs"

[[ -f "$launch_shader" ]] || fail "launch surface shader is missing"
has 'v_world_position = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz' "$launch_shader" "launch surface detail is not world-space stable"
has 'float aggregate = noise01' "$launch_shader" "launch surface has no aggregate breakup"
has 'float grain = noise01' "$launch_shader" "launch surface has no fine grain"
has 'CreateLaunchSurfaceMaterial' "$launch_pad" "launch pad does not bind procedural surface materials"
has 'ApplySurface("OrbitalPadApron"' "$launch_pad" "starbase apron is not textured"

has 'uniform float night_floor' "$shader" "Earth ground has no bounded indirect night floor"
has 'uniform sampler2D night_tex' "$shader" "Earth ground has no real night-side texture input"
has 'uniform float terrain_relief_strength' "$shader" "Earth ground has no bounded local relief control"
has 'v_patch        = patch_m;' "$shader" "Earth ground detail coordinate is not derived from the authoritative patch position"
has 'float macro = noise01' "$shader" "Earth ground has no multi-scale macro terrain breakup"
has 'float regional = noise01' "$shader" "Earth ground has no regional terrain breakup"
has 'float relief_scale = terrain_relief_strength * land_mask' "$shader" "Earth ground relief is not restricted to land"
has 'vec3 city_lights = night_map * city_mask * night_side' "$shader" "Earth ground city lights do not follow the night side"
has 'uniform float terminator_width' "$shader" "Earth ground has no bounded terminator transition"
has 'float terminator = smoothstep' "$shader" "Earth ground terminator transition is not explicit"
has 'vec3 direct = vec3(1.05 * ndl * solar_visibility)' "$shader" "Earth ground direct solar term is not visibility-gated"
has 'render_mode cull_back, unshaded, depth_draw_opaque' "$shader" "Earth ground must own its manual radiance on the opaque pass"
has 'earthshine_gain' "$shader" "Earth ground earthshine gain is missing"
has 'earthshine_min_reflectance' "$shader" "Earth ground minimum earthshine reflectance is missing"
has 'ground_radiance = lit + indirect_emission + city_lights' "$shader" "Earth ground earthshine is not composed into radiance"
has 'night_floor", NightFloor' "$controller" "Earth ground calibration is not configured from C#"
has 'private const float NightFloor = 0.12f;' "$controller" "Earth ground floor is not at the validated bounded ceiling"
has 'private const float EarthshineGain = 2.80f;' "$controller" "Earth ground earthshine gain is not configured"
has 'private const float EarthshineMinReflectance = 0.055f;' "$controller" "Earth ground minimum reflectance is not configured"
has 'private const float DetailStrength = 0.18f;' "$controller" "Earth ground detail strength is not configured"
has 'private const float TerrainReliefStrength = 0.18f;' "$controller" "Earth ground relief strength is not configured"
has 'private const float NightCityGain = 0.34f;' "$controller" "Earth ground city-light gain is not configured"
has 'earth_night.jpg' "$controller" "Earth ground does not bind the night texture"
has 'private const float CoastalGrade = 0.28f;' "$controller" "Earth ground coastal grade is not configured"
has 'private const float HorizonHazeStrength = 0.98f;' "$controller" "Earth ground horizon haze is too broad or unconfigured"
has 'HorizonHazeStrength' "$controller" "Earth ground horizon seam mitigation is not bounded/configured"
has 'private static readonly Color EarthHorizonFloor' "$controller" "Earth ground lacks a bounded upper-atmosphere limb floor"
has 'new(0.82f, 0.88f, 0.95f)' "$controller" "Earth ground limb floor is not shared with the sky daylight dome"
has 'Mathf.SmoothStep(-0.12f, 0.03f, renderUp.Dot(sunDirection))' "$controller" "Earth ground daylight floor is not gated by solar elevation"
has 'hazeColor = hazeColor.Lerp(EarthHorizonFloor, daylight)' "$controller" "Earth ground horizon floor does not converge with the sky daylight dome"

has 'GetSurfacePoint(vessel.Position, 0.0)' "$controller" "Earth ground is not anchored to the live ellipsoid surface"
has 'GetGeodeticUp(vessel.Position)' "$controller" "Earth ground does not use geodetic up"
has 'EarthGlobeAlpha' "$controller" "Earth ground fade is not complementary with the scaled-space globe"
has 'EarthVisualHandoffLowM = 12_000.0' "$origin" "Earth visual handoff low altitude changed"
has 'EarthVisualHandoffHighM = 18_000.0' "$origin" "Earth visual handoff high altitude changed"
has 'VisualSurfaceRadiusMetres' "$origin" "scaled-space Earth does not read live surface radius"
has 'BuildStarbaseFarField' "$launch_pad" "starbase far-field context is not built"
has 'FloatingOrigin.EarthGlobeAlpha(altitude)' "$far_field" "Starbase far-field is not coupled to the Earth handoff"
has 'CommodityTankMaxHeight' "$far_field" "Starbase far-field tank scale is not sourced from LaunchComplexSpec"
has 'float tankRadius = 4.2f' "$far_field" "Starbase far-field tank radius drifted from the hero farm"
has 'float site_core = 1.0 - smoothstep' "$shader" "Earth ground does not reconstruct land out to the play-camera horizon"
has 'float coastal_belt = 1.0 - smoothstep' "$shader" "Earth ground has no coastal belt beyond the pad island"
if rg -q 'StarbaseWetlandSkirt|StarbaseDuneShoulder|StarbaseCoastalFill' "$launch_pad"; then
  fail "starbase ground cookies are still authored in LaunchPadController"
fi
has 'uniform float edge_fade' "$launch_shader" "launch surface has no skirt edge fade"
has 'edgeFade: 1f' "$launch_pad" "starbase wetland skirt does not fade into the planetary patch"
has 'PatchRadiusUnits = 280_000f' "$controller" "Earth ground disc does not reach the geometric horizon"
has 'EarthVisualHandoffLowM = 12_000.0' "$origin" "scaled Earth handoff starts too late for the local terrain coverage"
has 'EarthVisualHandoffHighM = 18_000.0' "$origin" "scaled Earth handoff ends too late for the local terrain coverage"
has 'private const int   DiscRings        = 96;' "$controller" "Earth ground radial tessellation is too coarse"
has 'private const int   DiscSegments     = 256;' "$controller" "Earth ground horizon silhouette is too coarse"
has 'FadeCivilGroundBox' "$controller" "civil Ground/wetland cookie is not faded on ascent"
has 'LocalPatchOpacity' "$controller" "Earth ground does not expose compositor opacity"
has 'OrbitalPadApron' "$controller" "orbital pad apron cookie is not faded with the civil ground"
has 'float look_down = smoothstep' "$shader" "Earth ground nadir views still apply grazing haze"
has 'float horizon_path = max(horizon_dist * 0.32' "$shader" "Earth ground horizon extinction path is not bounded"
has 'float distance_haze = 1.0 - exp(-dist / horizon_path)' "$shader" "Earth ground horizon extinction is not monotonic"
has 'float distance_transmittance = 1.0 - distance_haze * 0.92' "$shader" "Earth ground distance haze is not composed in transmittance space"
has 'float grazing_transmittance = 1.0 - grazing_haze * horizon_haze_strength' "$shader" "Earth ground grazing haze is not composed in transmittance space"
has 'float haze = clamp(1.0 - distance_transmittance * grazing_transmittance' "$shader" "Earth ground haze composition has a discontinuous max transition"
has 'float horizon_m = max(horizon_dist * metres_per_unit' "$shader" "Earth ground rim is not a circular geometric-horizon fade"
has 'float radial_distance = length(uv - vec2(0.5)) * 2.0;' "$shader" "terrain raster handoffs still use square edge weighting"
has 'smoothstep(0.62, 0.80, texture(macro_mask_tex, uv).r)' "$shader" "macro provider feather tail can expose neutral JPEG fill"
has 'float macro_no_data_factor(vec2 uv)' "$shader" "macro JPEG no-data fill is not rejected"
has 'float regional_no_data_factor(vec2 uv)' "$shader" "regional JPEG no-data fill is not rejected"
has 'uniform sampler2D regional_ortho_tex' "$shader" "Earth ground has no real regional ortho texture input"
has 'uniform sampler2D regional_height_tex' "$shader" "Earth ground has no real regional elevation input"
has 'vec2 regional_uv(vec2 patch_m)' "$shader" "regional terrain is not mapped in the local geodetic frame"
has 'sample_height_m(regional_height_tex, regional' "$shader" "regional terrain relief is not sampled in the vertex path"
has 'surface = mix(surface, regional_surface, regional_weight)' "$shader" "regional ortho material does not own the local ground"
has 'RegionalTerrainReady' "$controller" "regional terrain asset readiness is not exposed"
has 'NAIP+3DEP:' "$controller" "regional terrain source is not visible in runtime diagnostics"
has 'terrainPrefix}_naip_10km_mask.png' "$controller" "NAIP no-data mask is not bound"
has 'terrainPrefix}_3dep_10km_height.png' "$controller" "3DEP height asset is not bound"
has 'uniform sampler2D macro_ortho_tex' "$shader" "Earth ground has no broad Starbase macro ortho input"
has 'uniform sampler2D macro_height_tex' "$shader" "Earth ground has no broad Starbase macro elevation input"
has 'vec2 macro_uv(vec2 patch_m)' "$shader" "macro terrain is not mapped in the local geodetic frame"
has 'sample_height_m(macro_height_tex, macro' "$shader" "macro terrain relief is not sampled in the vertex path"
has 'surface = mix(surface, macro_surface, macro_weight)' "$shader" "macro ortho material does not bridge the local handoff"
has 'MacroTerrainReady' "$controller" "macro terrain asset readiness is not exposed"
has 'macroPrefix}_naip_50km_mask.png' "$controller" "macro NAIP no-data mask is not bound"
has 'macroPrefix}_3dep_50km_height.png' "$controller" "macro 3DEP height asset is not bound"
[[ -f "$ROOT/assets/textures/starbase_naip_10km.jpg" ]] || fail "NAIP regional asset is missing"
[[ -f "$ROOT/assets/textures/starbase_naip_10km_mask.png" ]] || fail "NAIP regional mask is missing"
[[ -f "$ROOT/assets/textures/starbase_3dep_10km_height.png" ]] || fail "3DEP regional height asset is missing"
[[ -f "$ROOT/assets/textures/starbase_naip_50km.jpg" ]] || fail "NAIP macro asset is missing"
[[ -f "$ROOT/assets/textures/starbase_naip_50km_mask.png" ]] || fail "NAIP macro mask is missing"
[[ -f "$ROOT/assets/textures/starbase_3dep_50km_height.png" ]] || fail "3DEP macro height asset is missing"
[[ -f "$manifest" ]] || fail "regional terrain provenance manifest is missing"
has '"source": "USDA NAIP CONUS ImageServer"' "$manifest" "NAIP provenance is missing"
has '"source": "USGS 3DEP Elevation ImageServer"' "$manifest" "3DEP provenance is missing"
has '"runtime_extent_m": 10000.0' "$manifest" "regional terrain extent is undocumented"
has '"macro_runtime_extent_m": 50000.0' "$manifest" "macro terrain extent is undocumented"
has 'PadShadowMaxDistance = 1_100f' "$lighting" "pad directional shadows do not cover the tower/stack"
has 'ShadowMode.Parallel4Splits' "$lighting" "pad shadows do not preserve near-field contact detail"
has 'DirectionalShadowSplit1 = 0.08f' "$lighting" "pad shadow cascades are not biased toward nearby geometry"
has 'ShadowNormalBias, 0.45f' "$lighting" "pad shadow normal bias is too detached from contact surfaces"
has 'LightAngularDistance, 0.53f' "$lighting" "sun shadows do not use the real solar angular diameter"
has 'AmbientLightSkyContribution = AmbientSkyContribution' "$lighting" "procedural sky does not contribute ambient light"
has 'ReflectedLightSource = Godot.Environment.ReflectionSource.Sky' "$lighting" "procedural sky is not a specular reflection source"
has 'FogMode = Godot.Environment.FogModeEnum.Depth' "$lighting" "early flight has no bounded depth haze"
has 'UpdateAerialPerspective(1.0f - s)' "$lighting" "depth haze does not fade with atmospheric density"
has '_env.SsaoEnabled = forwardPlus || renderer == "gl_compatibility"' "$lighting" "ambient occlusion is not restricted to supported renderers"
has '_env.SsilEnabled = forwardPlus' "$lighting" "Forward+ indirect lighting is not renderer-gated"
has '_env.SsrEnabled = forwardPlus' "$lighting" "Forward+ reflections are not renderer-gated"
has 'RadialSegments = 384' "$origin" "scaled-space Earth globe is still the low-tessellation sawtooth sphere"
has 'float limb_aa = max(fwidth(limb)' "$surface" "Earth limb has no fwidth antialias against the sky"
has 'render_mode cull_back, unshaded, blend_mix' "$surface" "Earth limb ALPHA is ignored without blend_mix"

echo "earth_ground_lighting_contract_test: PASS (bounded night floor, ellipsoid disc, nadir haze gate, limb blend_mix)"
