#!/usr/bin/env bash
# State-gated pad→orbit→EDL visual play harness for Exosphere.
# Generates a temporary scripts/_PlaytestShot.cs autoload, runs Godot under xvfb,
# writes PNG milestones + /tmp/exo_play.log, and always cleans up on exit.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DEFAULT_GODOT="/home/sebasvelace/Downloads/Godot_v4.6.3-stable_mono_linux_x86_64/Godot_v4.6.3-stable_mono_linux.x86_64"
GODOT="${GODOT_BIN:-$DEFAULT_GODOT}"
HARNESS="scripts/_PlaytestShot.cs"
OUT_DIR="${OUT_DIR:-/tmp/exo_play}"
LOG="${LOG:-/tmp/exo_play.log}"
MODE="full"
SKIP_BUILD=0
PROJECT_BACKUP=""

usage() {
  cat <<'EOF'
Usage: tools/visual_playtest.sh [options]

Runs the Exosphere visual playtest harness (temporary autoload, never committed).

Options:
  --smoke       Pad-only capture (~30s). Used by CI for pipeline validation.
  --launch      Capture ignition and early vertical liftoff, then exit.
  --ship        Stage immediately and capture powered standalone Starship in vacuum.
  --cockpit     Capture the first-person cockpit optics and interior.
  --atmosphere  Capture a deterministic day/twilight/night altitude matrix with image metrics.
  --edl         Seed a deterministic 70 km entry and verify physical flip/touchdown.
  --out-dir DIR PNG output directory (default: /tmp/exo_play)
  --log FILE    Telemetry log path (default: /tmp/exo_play.log)
  --skip-build  Skip the simulation-library prebuild (the Godot project is still built)
  -h, --help    Show this help

Environment:
  GODOT_BIN     Path to Godot 4.6 mono binary

Outputs:
  ${OUT_DIR}/exo_play_<milestone>.png
  ${LOG}         One telemetry line per captured milestone + summary

Cleanup on exit (success or failure):
  removes scripts/_PlaytestShot.cs (+ .uid), restores project.godot
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --smoke) MODE="smoke"; shift ;;
    --launch) MODE="launch"; shift ;;
    --ship) MODE="ship"; shift ;;
    --cockpit) MODE="cockpit"; shift ;;
    --atmosphere) MODE="atmosphere"; shift ;;
    --edl) MODE="edl"; shift ;;
    --out-dir) OUT_DIR="$2"; shift 2 ;;
    --log) LOG="$2"; shift 2 ;;
    --skip-build) SKIP_BUILD=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

cleanup() {
  local ec=$?
  rm -f "$HARNESS" "${HARNESS}.uid" 2>/dev/null || true
  if [[ -n "$PROJECT_BACKUP" && -f "$PROJECT_BACKUP" ]]; then
    cp "$PROJECT_BACKUP" project.godot
    rm -f "$PROJECT_BACKUP"
  fi
  if [[ $ec -ne 0 ]]; then
    echo "visual_playtest: failed (exit $ec). Harness cleaned; project.godot restored." >&2
  fi
  exit "$ec"
}
trap cleanup EXIT INT TERM

if [[ ! -x "$GODOT" ]]; then
  echo "ERROR: Godot not found at $GODOT (set GODOT_BIN)" >&2
  exit 1
fi
if ! command -v xvfb-run >/dev/null 2>&1; then
  echo "ERROR: xvfb-run not found (install xvfb)" >&2
  exit 1
fi

register_autoload() {
  if grep -q 'PlaytestShot=' project.godot 2>/dev/null; then
    return
  fi
  PROJECT_BACKUP="$(mktemp /tmp/exo_project_godot.XXXXXX)"
  cp project.godot "$PROJECT_BACKUP"
  if grep -q '^\[autoload\]' project.godot; then
    sed -i '/^\[autoload\]/a PlaytestShot="*res://scripts/_PlaytestShot.cs"' project.godot
  else
    cat >> project.godot <<'EOF'

[autoload]

PlaytestShot="*res://scripts/_PlaytestShot.cs"
EOF
  fi
}

write_harness() {
  mkdir -p "$(dirname "$HARNESS")"
  cat > "$HARNESS" <<CS
namespace Exosphere.Game;

using Godot;
using System;
using System.IO;
using System.Linq;
using Exosphere.Simulation;
using Exosphere.Simulation.Math;
using Exosphere.Simulation.Physics;

/// <summary>
/// Temporary visual playtest autoload — generated by tools/visual_playtest.sh; never commit.
/// </summary>
public partial class _PlaytestShot : Node
{
    const double FluxPeak = 6.0e5;
    const int SettleFrames = 4;
    const double MaxRuntimeSec = 1800.0;
    const double AscentFallbackSec = 480.0;

    readonly string _mode;
    readonly string _outDir;

    StreamWriter _log = null!;
    double _t0;
    int _frame;
    int _readyFrames;
    int _settleLeft;
    string? _pendingSlug;

    bool _pad, _liftoff, _maxq, _separation, _orbit, _orbitBeauty;
    bool _entry, _peak, _retro, _landed;
    bool _ascentEngaged, _deorbitStarted, _deorbitDone, _ascentFallbackUsed;
    bool _beautyJumped;
    int _beautyWaitFrames;
    bool _edlSeeded, _flipComplete, _shipSeeded;
    double _edlScenarioStart, _retroStart = -1.0, _nextEdlTelemetry;
    bool _finished;

    // Atmosphere acceptance is deliberately state-seeded instead of flown.  This makes
    // every altitude/solar-elevation pair reproducible and keeps the matrix fast enough
    // to run while tuning the scattering shader.  Cockpit cases are last because the
    // public camera API intentionally only enters (rather than exits) IVA mode.
    readonly (string Slug, double AltitudeM, double SunElevationDeg, bool Cockpit)[] _atmosCases =
    {
        ("ground_day",       20.0,  45.0, false),
        ("ground_sunrise",   20.0,  -1.0, false),
        ("ground_sunset",    20.0,   1.0, false),
        ("ground_night",     20.0, -35.0, false),
        ("10km_day",     10_000.0,  35.0, false),
        ("30km_day",     30_000.0,  35.0, false),
        ("70km_day",     70_000.0,  35.0, false),
        ("120km_day",   120_000.0,  35.0, false),
        ("400km_day",   400_000.0,  35.0, false),
        ("10km_night",   10_000.0, -35.0, false),
        ("30km_night",   30_000.0, -35.0, false),
        ("70km_night",   70_000.0, -35.0, false),
        ("120km_night", 120_000.0, -35.0, false),
        ("400km_night", 400_000.0, -35.0, false),
        ("cockpit_120km_day",   120_000.0,  35.0, true),
        ("cockpit_120km_night", 120_000.0, -35.0, true),
    };
    const int AtmosphereMinimumSettleFrames = 8;
    const int AtmosphereMaximumSettleFrames = 180;
    const double AtmosphereSettleSeconds = 1.2;
    int _atmosIndex = -1;
    Vector3d _atmosUp = Vector3d.Up, _atmosLook = Vector3d.Forward;
    double _atmosFrameSeconds, _atmosMaxFrameSeconds;
    int _atmosPerfFrames, _atmosSlowFrames;

    public _PlaytestShot()
    {
        _mode = "${MODE}";
        _outDir = "${OUT_DIR}";
    }

    public override void _Ready()
    {
        Directory.CreateDirectory(_outDir);
        _log = new StreamWriter("${LOG}", false);
        _log.WriteLine($"=== Exosphere visual playtest {DateTime.UtcNow:O} mode={_mode} ===");
        _log.Flush();
        _t0 = Time.GetTicksMsec() / 1000.0;
        ProcessMode = ProcessModeEnum.Always;
    }

    public override void _Process(double delta)
    {
        if (_finished) return;
        _frame++;

        double elapsed = Time.GetTicksMsec() / 1000.0 - _t0;
        if (elapsed > MaxRuntimeSec) { Finish("TIMEOUT"); return; }

        var bridge = SimulationBridge.Instance;
        var vessel = bridge?.ActiveVessel;
        var universe = bridge?.Universe;
        if (bridge == null || vessel == null || universe == null)
        {
            if (_frame > 6000) Finish("NO_BRIDGE");
            return;
        }

        _readyFrames++;
        var body = universe.GetDominantBody(vessel.Position);
        if (body == null) return;

        double alt = vessel.GetAltitude(body);
        Vector3d surfVel = vessel.GetSurfaceVelocity(body);
        Vector3d up = (vessel.Position - body.Position).Normalized;
        double spd = surfVel.Magnitude;
        double vSpeed = surfVel.Dot(up);
        double q = vessel.GetDynamicPressure(body);
        double mass = System.Math.Max(vessel.TotalMass, 1.0);
        Vector3d nonGrav = (vessel.ComputeThrust(body) + vessel.ComputeDrag(body)) / mass;
        double g = nonGrav.Magnitude / 9.80665;
        var mission = MissionManager.Instance;
        string phase = mission?.Phase.ToString() ?? "UNKNOWN";
        double maxT = vessel.Parts.Parts.Count > 0 ? vessel.Parts.Parts.Max(p => p.Temperature) : 0.0;
        double heatRatio = vessel.Parts.Parts.Count > 0 ? vessel.Parts.Parts.Max(p => p.ThermalRatio) : 0.0;
        double density = body.GetAtmosphericDensity(vessel.Position);
        double flux = ThermalModel.ComputeHeatFlux(density, spd);
        double fluxRatio = flux / FluxPeak;

        TryCapturePending();

        if (_mode == "atmosphere")
        {
            ProcessAtmosphereMatrix(delta, bridge, vessel, universe, body);
            return;
        }

        if (_mode == "cockpit")
        {
            CameraController.Instance?.EnterCockpitView();
            if (!_shipSeeded && _readyFrames >= 45)
            {
                bridge.TriggerStaging();
                bridge.JumpToOrbit(118_000.0);
                bridge.SetThrottle(0.35);
                _shipSeeded = true;
                return;
            }
            if (_shipSeeded && _pendingSlug == null && _readyFrames >= 110 && !_orbitBeauty)
            {
                QueueCapture("cockpit");
                _orbitBeauty = true;
            }
            if (_orbitBeauty && _pendingSlug == null)
                Finish("COCKPIT_OK");
            return;
        }

        if (_mode == "ship")
        {
            if (!_shipSeeded && _readyFrames >= 45)
            {
                bridge.TriggerStaging();
                bridge.JumpToOrbit(118_000.0);
                bridge.SetThrottle(1.0);
                _shipSeeded = true;
                return;
            }
            if (_shipSeeded && _pendingSlug == null && _readyFrames >= 110 && !_orbitBeauty)
            {
                QueueCapture("ship_vacuum");
                _orbitBeauty = true;
            }
            if (_orbitBeauty && _pendingSlug == null)
                Finish("SHIP_OK");
            return;
        }

        if (_mode == "smoke")
        {
            if (!_pad && _readyFrames >= 45)
            {
                QueueCapture("pad");
                _pad = true;
            }
            if (_pad && _pendingSlug == null)
                Finish("SMOKE_OK");
            return;
        }

        if (_mode == "edl")
        {
            ProcessEdlVerification(bridge, vessel, universe, body, mission, alt, surfVel, phase);
            return;
        }

        // ── Pad ───────────────────────────────────────────────────────────────
        if (!_pad && _readyFrames >= 45 && alt is > 5.0 and < 40.0)
        {
            QueueCapture("pad");
            _pad = true;
        }

        // ── Ascent autopilot ──────────────────────────────────────────────────
        if (_pad && !_ascentEngaged && AscentController.Instance != null)
        {
            AscentController.Instance.Engage();
            _ascentEngaged = true;
            _log.WriteLine("ACTION engage AscentController [G] autopilot");
            _log.Flush();
        }

        if (!_liftoff && alt is >= 80.0 and <= 350.0 &&
            mission?.Phase is MissionPhase.LIFTOFF or MissionPhase.ASCENT_SH or MissionPhase.IGNITION)
        {
            QueueCapture("liftoff");
            _liftoff = true;
        }

        if (_mode == "launch" && _liftoff && _pendingSlug == null)
        {
            Finish("LAUNCH_OK");
            return;
        }

        if (!_maxq && mission?.Phase == MissionPhase.MAX_Q)
        {
            QueueCapture("maxq");
            _maxq = true;
        }

        if (!_separation && mission?.Phase is MissionPhase.SEPARATION or MissionPhase.MECO or MissionPhase.ASCENT_SHIP)
        {
            QueueCapture("separation");
            _separation = true;
        }

        if (!_orbit && mission?.Phase == MissionPhase.ORBIT)
        {
            QueueCapture("orbit");
            _orbit = true;
        }

        // Fallback: if ascent takes too long, teleport to orbit for downstream milestones.
        if (!_orbit && !_ascentFallbackUsed && elapsed > AscentFallbackSec &&
            mission?.Phase is MissionPhase.PRE_LAUNCH or MissionPhase.COUNTDOWN or MissionPhase.IGNITION
                or MissionPhase.LIFTOFF or MissionPhase.ASCENT_SH or MissionPhase.MAX_Q or MissionPhase.MECO
                or MissionPhase.SEPARATION or MissionPhase.ASCENT_SHIP)
        {
            bridge.JumpToOrbit(200_000.0);
            _ascentFallbackUsed = true;
            _orbit = true;
            QueueCapture("orbit");
            _log.WriteLine("FALLBACK JumpToOrbit(200km) — ascent did not reach ORBIT in time");
            _log.Flush();
        }

        // ── Orbit beauty shot ─────────────────────────────────────────────────
        if (_orbit && !_beautyJumped && _pendingSlug == null)
        {
            bridge.JumpToOrbit(250_000.0);
            bridge.SetTimeScale(1.0);
            _beautyJumped = true;
            _beautyWaitFrames = 60;
            _deorbitStarted = false;
            _deorbitDone = false;
        }

        if (_beautyJumped && !_orbitBeauty && _beautyWaitFrames > 0)
            _beautyWaitFrames--;

        if (_beautyJumped && !_orbitBeauty && _beautyWaitFrames == 0 && _pendingSlug == null)
        {
            QueueCapture("orbit_beauty");
            _orbitBeauty = true;
        }

        // ── Deorbit → EDL (best effort) ───────────────────────────────────────
        if (_orbitBeauty && _pendingSlug == null && !_landed && !vessel.IsDestroyed)
            ProcessDeorbit(bridge, vessel, universe, body, mission, alt);

        if (!_entry && mission?.Phase == MissionPhase.ENTRY)
        {
            QueueCapture("entry");
            _entry = true;
        }

        if (!_peak && mission?.Phase == MissionPhase.PEAK_HEATING)
        {
            QueueCapture("peak_heating");
            _peak = true;
        }

        if (!_retro && mission?.Phase == MissionPhase.RETRO_BURN)
        {
            QueueCapture("retro_burn");
            _retro = true;
        }

        if (!_landed && mission?.Phase == MissionPhase.LANDED)
        {
            QueueCapture("touchdown");
            _landed = true;
        }

        if (vessel.IsDestroyed)
        {
            _log.WriteLine($"FAIL vessel destroyed phase={phase} alt={alt:F0} spd={spd:F0} heatRatio={heatRatio:F3} maxT={maxT:F0}");
            _log.Flush();
            Finish("CRASHED");
            return;
        }

        if (_landed && _pendingSlug == null)
        {
            Finish("LANDED");
            return;
        }

        // End when robust milestones done and EDL did not activate in time.
        if (_orbitBeauty && _pendingSlug == null && !_landed && elapsed > 720.0 && !_entry)
        {
            _log.WriteLine("GAP deorbit→EDL: no ENTRY phase reached within 720s (see PLAN_PLAYTEST.md milestone 7)");
            _log.Flush();
            Finish("EDL_GAP");
        }
    }

    private void ProcessEdlVerification(SimulationBridge bridge, Vessel vessel, Universe universe,
        CelestialBody body, MissionManager? mission, double alt, Vector3d surfVel, string phase)
    {
        if (!_edlSeeded)
        {
            if (_readyFrames < 30 || EDLController.Instance == null) return;

            // Exercise the exact public entry point used by the HUD button/[R], rather than
            // maintaining a second private seed that could silently drift from gameplay.
            if (!bridge.BeginReentryDemonstration())
            {
                _log.WriteLine("GAP HUD reentry demonstration entry point refused the scenario");
                Finish("EDL_DEMO_START_FAILED");
                return;
            }
            vessel = bridge.ActiveVessel!;
            body = universe.Bodies.First(b => b.Name == "Earth");
            bridge.SetTimeScale(3.0); // verification speed only; the HUD button starts at x1

            _edlSeeded = true;
            _edlScenarioStart = universe.CurrentTime;
            _log.WriteLine("ACTION seeded deterministic EDL alt=70000m airspeed=1804m/s reserve=12%");
            _log.Flush();
            return;
        }

        double simElapsed = universe.CurrentTime - _edlScenarioStart;
        if (simElapsed >= _nextEdlTelemetry)
        {
            Vector3d up = (vessel.Position - body.Position).Normalized;
            double vUp = surfVel.Dot(up);
            double horizontal = (surfVel - up * vUp).Magnitude;
            var cluster = vessel.Parts.Parts.FirstOrDefault(p => p.Definition.Id == "starship_engines");
            double upright = vessel.Orientation.Rotate(Vector3d.Up).Normalized.Dot(up);
            int contacts = vessel.LastSurfaceContact?.ContactCount ?? 0;
            double maxStroke = vessel.LastSurfaceContact?.Points.Max(p => p.PenetrationM) ?? 0.0;
            double peakLegLoad = vessel.LastSurfaceContact?.Points.Max(p => p.NormalLoadN) ?? 0.0;
            _log.WriteLine($"TRACE t={simElapsed:F1} alt={alt:F1} vUp={vUp:F1} horiz={horizontal:F1} " +
                $"throttle={vessel.Throttle:F3} spool={cluster?.ThrottleLevel ?? 0.0:F3} " +
                $"engines={cluster?.SelectedEngineCount ?? 0} upright={upright:F4} phase={phase} " +
                $"contacts={contacts} maxStroke={maxStroke:F3} peakLegLoad={peakLegLoad:F0} " +
                $"settled={vessel.IsSurfaceSettled}");
            _log.Flush();
            _nextEdlTelemetry = simElapsed + 5.0;
        }

        if (!_entry && mission?.Phase is MissionPhase.ENTRY or MissionPhase.PEAK_HEATING
                or MissionPhase.AERO_DESCENT or MissionPhase.RETRO_BURN
                or MissionPhase.FINAL_DESCENT or MissionPhase.LANDED)
        {
            QueueCapture("entry");
            _entry = true;
        }

        if (!_peak && mission?.Phase == MissionPhase.PEAK_HEATING)
        {
            QueueCapture("peak_heating");
            _peak = true;
        }

        if (!_retro && mission?.Phase is MissionPhase.RETRO_BURN or MissionPhase.FINAL_DESCENT)
        {
            QueueCapture("retro_burn");
            _retro = true;
            _retroStart = universe.CurrentTime;
        }

        if (_retro && !_flipComplete && _pendingSlug == null && surfVel.Magnitude > 1.0)
        {
            Vector3d nose = vessel.Orientation.Rotate(Vector3d.Up).Normalized;
            double alignment = nose.Dot(-surfVel.Normalized);
            if (alignment > System.Math.Cos(5.0 * System.Math.PI / 180.0) &&
                universe.CurrentTime - _retroStart > 0.5)
            {
                QueueCapture("flip_complete");
                _flipComplete = true;
                int engines = vessel.Parts.Parts
                    .FirstOrDefault(p => p.Definition.Id == "starship_engines")?.SelectedEngineCount ?? 0;
                _log.WriteLine($"CHECK finite_flip duration={universe.CurrentTime - _retroStart:F2}s " +
                    $"alignment={alignment:F5} omega={vessel.AngularVelocity.Magnitude:F4} engines={engines}");
                _log.Flush();
            }
        }

        if (!_landed && mission?.Phase == MissionPhase.LANDED)
        {
            QueueCapture("touchdown");
            _landed = true;
        }

        if (vessel.IsDestroyed)
        {
            var contact = vessel.LastSurfaceContact;
            int contacts = contact?.ContactCount ?? 0;
            double maxStroke = contact?.Points.Max(p => p.PenetrationM) ?? 0.0;
            double peakLegLoad = contact?.Points.Max(p => p.NormalLoadN) ?? 0.0;
            _log.WriteLine($"FAIL vessel destroyed phase={phase} alt={alt:F1} " +
                $"spd={surfVel.Magnitude:F2} cause={vessel.DestructionCause} " +
                $"impact={vessel.CrashImpactSpeed:F2} gear={vessel.HasDeployedLandingGear} " +
                $"points={vessel.LandingContactPoints.Count} contacts={contacts} " +
                $"maxStroke={maxStroke:F3} peakLegLoad={peakLegLoad:F0} " +
                $"travelExcess={contact?.MaxTravelExcessM ?? 0.0:F3} " +
                $"overTravel={contact?.HasOverTravel ?? false} overload={contact?.HasOverload ?? false}");
            _log.Flush();
            Finish("CRASHED");
            return;
        }

        if (_landed && _pendingSlug == null)
        {
            Finish(_flipComplete ? "LANDED" : "LANDED_WITHOUT_FLIP");
            return;
        }

        if (simElapsed > 900.0)
            Finish("EDL_TIMEOUT");
    }

    private void ProcessDeorbit(SimulationBridge bridge, Vessel vessel, Universe universe,
        CelestialBody body, MissionManager? mission, double alt)
    {
        if (!_deorbitStarted)
        {
            DrainToReserve(vessel, 0.08);
            bridge.SetTimeScale(1.0);
            _deorbitStarted = true;
            _log.WriteLine("ACTION deorbit: drained to ~8% reserve, starting retro burn");
            _log.Flush();
        }

        Vector3d rel = vessel.Position - body.Position;
        Vector3d vel = vessel.Velocity - body.Velocity;
        var oe = OrbitalElements.FromStateVector(rel, vel, body.GM, body.Id, universe.CurrentTime);
        double periAlt = oe.Periapsis - body.Radius;

        if (!_deorbitDone)
        {
            Vector3d surfVel = vessel.GetSurfaceVelocity(body);
            Vector3d retro = surfVel.Magnitude > 10.0 ? -surfVel.Normalized : -rel.Normalized;
            vessel.Orientation = ShortestArc(Vector3d.Up, retro);
            vessel.Throttle = 1.0;
            vessel.SASEnabled = false;
            // Commit the entry: a shallow periapsis (~64 km) grazes and can skip back out of
            // the atmosphere, re-coasting a full orbit and blowing the wall budget. Target
            // ~55 km so the belly-flop enters on a single committed pass (survivable corridor
            // for a high-drag broadside attitude) and reaches touchdown in a few sim-minutes.
            if (periAlt < 55_000.0)
            {
                vessel.Throttle = 0.0;
                _deorbitDone = true;
                _log.WriteLine($"ACTION deorbit burn complete periAlt={periAlt / 1000.0:F0} km");
                _log.Flush();
            }
        }
        else if (alt > 120_000.0 && vessel.Throttle < 0.01 && mission?.InDescent != true)
        {
            // Coast to the entry interface fast regardless of the exact mission-phase label.
            // The old gate required Phase==ORBIT, but the deorbit burn can leave ORBIT while
            // apoapsis is still high, stranding a ~90 min coast at 1x and blowing the wall budget.
            bridge.SetTimeScale(200.0);
        }
        else
        {
            // Entry interface reached (below 120 km or descent armed): real-time so RK4 aero/
            // heating runs and ENTRY/PEAK_HEATING/RETRO_BURN/LANDED phases fire for capture.
            bridge.SetTimeScale(1.0);
        }
    }

    private void ProcessAtmosphereMatrix(double delta, SimulationBridge bridge,
        Vessel vessel, Universe universe, CelestialBody body)
    {
        if (_readyFrames < 60) return;

        if (_atmosIndex < 0)
        {
            _atmosIndex = 0;
            ApplyAtmosphereCase(bridge, vessel, universe, body);
        }

        _atmosFrameSeconds += delta;
        _atmosMaxFrameSeconds = System.Math.Max(_atmosMaxFrameSeconds, delta);
        _atmosPerfFrames++;
        if (delta > 1.0 / 30.0) _atmosSlowFrames++;

        ApplyAtmosphereCamera();
        // Wall-clock settling makes the harness practical both on a real GPU (~60 fps)
        // and CI's llvmpipe renderer (~2 fps).  Always allow several incremental sky
        // cubemap updates, but never wait hundreds of slow software-rendered frames.
        bool enoughFrames = _atmosPerfFrames >= AtmosphereMinimumSettleFrames;
        bool enoughTime = _atmosFrameSeconds >= AtmosphereSettleSeconds;
        bool safetyLimit = _atmosPerfFrames >= AtmosphereMaximumSettleFrames;
        if (!safetyLimit && !(enoughFrames && enoughTime)) return;

        var shot = _atmosCases[_atmosIndex];
        CaptureNow(shot.Slug);
        LogAtmosphereState(bridge, vessel, universe, body, shot);

        _atmosIndex++;
        if (_atmosIndex >= _atmosCases.Length)
        {
            Finish("ATMOSPHERE_OK");
            return;
        }
        ApplyAtmosphereCase(bridge, vessel, universe, body);
    }

    private void ApplyAtmosphereCase(SimulationBridge bridge, Vessel vessel,
        Universe universe, CelestialBody earth)
    {
        var shot = _atmosCases[_atmosIndex];
        var sun = universe.GetBody("sun");
        Vector3d sunDir = sun == null
            ? new Vector3d(0.4, 0.5, 0.8).Normalized
            : (sun.Position - earth.Position).Normalized;

        // Choose a stable vector on the terminator, then tilt it by the requested solar
        // elevation.  The resulting dot(up,sunDir) is exactly sin(elevation).
        Vector3d seed = System.Math.Abs(sunDir.Dot(Vector3d.Up)) < 0.92
            ? Vector3d.Up : Vector3d.Right;
        Vector3d terminatorUp = (seed - sunDir * seed.Dot(sunDir)).Normalized;
        double elev = shot.SunElevationDeg * System.Math.PI / 180.0;
        _atmosUp = (terminatorUp * System.Math.Cos(elev)
            + sunDir * System.Math.Sin(elev)).Normalized;

        Vector3d projectedSun = sunDir - _atmosUp * sunDir.Dot(_atmosUp);
        if (projectedSun.MagnitudeSquared < 1e-10)
            projectedSun = earth.GetEastDirection(earth.Position + _atmosUp * earth.Radius);
        _atmosLook = projectedSun.Normalized;

        vessel.IsGroundHeld = false;
        vessel.Position = earth.Position + _atmosUp * (earth.Radius + shot.AltitudeM);
        // Co-rotate with the sampled surface so q/heat telemetry remains zero.  The matrix
        // validates optics, not an accidental 350–460 m/s wind caused by inertial rest.
        vessel.Velocity = earth.Velocity + earth.GetSurfaceVelocity(vessel.Position);
        vessel.Throttle = 0.0;

        // Local +Y looks along the horizon; local -Z is radial-up.  This also gives the
        // cockpit cases a deterministic, level attitude rather than a random roll.
        Vector3d localXWorld = _atmosLook.Cross(-_atmosUp).Normalized;
        var basis = new Basis(ToGodot(localXWorld), ToGodot(_atmosLook), ToGodot(-_atmosUp));
        var q = basis.GetRotationQuaternion();
        vessel.Orientation = new Quaterniond(q.W, q.X, q.Y, q.Z);

        bridge.SetTimeScale(0.0);
        if (GetTree().Root.FindChild("HUDController", true, false) is CanvasItem hud)
            hud.Visible = false;
        if (shot.Cockpit)
        {
            if (CameraController.Instance != null)
                CameraController.Instance.ProcessMode = ProcessModeEnum.Inherit;
            CameraController.Instance?.EnterCockpitView();
        }

        _atmosFrameSeconds = 0.0;
        _atmosMaxFrameSeconds = 0.0;
        _atmosPerfFrames = 0;
        _atmosSlowFrames = 0;
        _log.WriteLine($"ATMOS_APPLY slug={shot.Slug} targetAlt={shot.AltitudeM:F1} " +
            $"targetSunElevation={shot.SunElevationDeg:F1} cockpit={shot.Cockpit}");
        _log.Flush();
    }

    private void ApplyAtmosphereCamera()
    {
        var shot = _atmosCases[_atmosIndex];
        if (shot.Cockpit) return;

        if (CameraController.Instance != null)
            CameraController.Instance.ProcessMode = ProcessModeEnum.Disabled;
        if (GetTree().Root.FindChild("StarshipRenderer", true, false) is Node3D renderer)
            renderer.Visible = false;
        if (GetTree().Root.FindChild("CockpitRenderer", true, false) is Node3D cockpit)
            cockpit.Visible = false;

        if (GetTree().Root.FindChild("Camera3D", true, false) is Camera3D camera)
        {
            camera.Position = Vector3.Zero;
            camera.Near = 0.1f;
            camera.Fov = 60.0f;
            camera.LookAt(ToGodot(_atmosLook) * 100.0f, ToGodot(_atmosUp));
        }
    }

    private void LogAtmosphereState(SimulationBridge bridge, Vessel vessel,
        Universe universe, CelestialBody earth,
        (string Slug, double AltitudeM, double SunElevationDeg, bool Cockpit) shot)
    {
        var sun = universe.GetBody("sun");
        Vector3d up = (vessel.Position - earth.Position).Normalized;
        Vector3d sunDir = sun == null ? Vector3d.Up : (sun.Position - vessel.Position).Normalized;
        double solarElevation = System.Math.Asin(System.Math.Clamp(up.Dot(sunDir), -1.0, 1.0))
            * 180.0 / System.Math.PI;
        var camera = GetTree().Root.FindChild("Camera3D", true, false) as Camera3D;
        var world = GetTree().Root.FindChild("WorldEnvironment", true, false) as WorldEnvironment;
        float exposure = world?.Environment?.TonemapExposure ?? -1.0f;
        double meanMs = _atmosPerfFrames > 0
            ? _atmosFrameSeconds * 1000.0 / _atmosPerfFrames : 0.0;

        _log.WriteLine($"ATMOS_STATE slug={shot.Slug} actualAlt={vessel.GetAltitude(earth):F1} " +
            $"sunElevation={solarElevation:F2} solarVisibility={SunController.SolarVisibility:F3} " +
            $"cockpit={shot.Cockpit} exposure={exposure:F3} fov={camera?.Fov ?? -1:F2} " +
            $"near={camera?.Near ?? -1:F3}");
        _log.WriteLine($"PERF slug={shot.Slug} meanFrameMs={meanMs:F2} " +
            $"maxFrameMs={_atmosMaxFrameSeconds * 1000.0:F2} slowFrames={_atmosSlowFrames} " +
            $"sampleFrames={_atmosPerfFrames} reportedFps={Engine.GetFramesPerSecond()}");
        _log.Flush();
    }

    private static Vector3 ToGodot(Vector3d value) => new(
        (float)value.X, (float)value.Y, (float)value.Z);

    private void QueueCapture(string slug)
    {
        if (_pendingSlug != null) return;
        _pendingSlug = slug;
        _settleLeft = SettleFrames;
    }

    private void TryCapturePending()
    {
        if (_pendingSlug == null) return;
        if (_settleLeft > 0) { _settleLeft--; return; }
        string slug = _pendingSlug;
        _pendingSlug = null;
        CaptureNow(slug);
    }

    private void CaptureNow(string slug)
    {
        var img = GetTree().Root.GetViewport().GetTexture().GetImage();
        string path = Path.Combine(_outDir, $"exo_play_{slug}.png");
        img.SavePng(path);
        LogTelemetry(slug, path);
        LogImageMetrics(slug, img);
        GD.Print($"[Playtest] captured {slug} -> {path}");
    }

    private void LogImageMetrics(string slug, Image image)
    {
        int width = image.GetWidth();
        int height = image.GetHeight();
        const int stride = 4;
        long samples = 0, clipped = 0, dark = 0, starCandidates = 0, starSamples = 0;
        double sum = 0.0, upperSum = 0.0, lowerSum = 0.0;
        long upperN = 0, lowerN = 0;
        int[] histogram = new int[256];

        for (int y = 0; y < height; y += stride)
        {
            for (int x = 0; x < width; x += stride)
            {
                Color c = image.GetPixel(x, y);
                double luma = 0.2126 * c.R + 0.7152 * c.G + 0.0722 * c.B;
                sum += luma;
                samples++;
                histogram[System.Math.Clamp((int)System.Math.Round(luma * 255.0), 0, 255)]++;
                if (System.Math.Max(c.R, System.Math.Max(c.G, c.B)) >= 0.995f) clipped++;
                if (luma <= 0.02) dark++;

                if (y < height * 0.42)
                {
                    upperSum += luma;
                    upperN++;
                }
                // Local-contrast star proxy, sampled in a central sky ROI that excludes the
                // corner HUD and top mission banner.  This distinguishes point-like stars
                // from a uniformly bright daytime sky much better than raw brightness.
                if (x >= width * 0.20 && x < width * 0.80
                    && y >= height * 0.15 && y < height * 0.48)
                {
                    double neighbours = 0.25 * (
                        Luma(image.GetPixel(System.Math.Max(0, x - stride), y))
                        + Luma(image.GetPixel(System.Math.Min(width - 1, x + stride), y))
                        + Luma(image.GetPixel(x, System.Math.Max(0, y - stride)))
                        + Luma(image.GetPixel(x, System.Math.Min(height - 1, y + stride))));
                    starSamples++;
                    if (luma > 0.10 && luma - neighbours > 0.08) starCandidates++;
                }
                if (y > height * 0.58)
                {
                    lowerSum += luma;
                    lowerN++;
                }
            }
        }

        double mean = samples > 0 ? sum / samples : 0.0;
        double upper = upperN > 0 ? upperSum / upperN : 0.0;
        double lower = lowerN > 0 ? lowerSum / lowerN : 0.0;
        _log.WriteLine($"IMAGE slug={slug} width={width} height={height} samples={samples} " +
            $"mean={mean:F5} p50={HistogramPercentile(histogram, samples, 0.50):F5} " +
            $"p95={HistogramPercentile(histogram, samples, 0.95):F5} " +
            $"clippedFrac={(samples > 0 ? (double)clipped / samples : 0.0):F5} " +
            $"darkFrac={(samples > 0 ? (double)dark / samples : 0.0):F5} " +
            $"upperMean={upper:F5} lowerMean={lower:F5} " +
            $"horizonContrast={System.Math.Abs(upper - lower):F5} " +
            $"starCandidateFrac={(starSamples > 0 ? (double)starCandidates / starSamples : 0.0):F6}");
        _log.Flush();
    }

    private static double Luma(Color c) =>
        0.2126 * c.R + 0.7152 * c.G + 0.0722 * c.B;

    private static double HistogramPercentile(int[] histogram, long samples, double fraction)
    {
        if (samples <= 0) return 0.0;
        long target = (long)System.Math.Ceiling(samples * fraction);
        long count = 0;
        for (int i = 0; i < histogram.Length; i++)
        {
            count += histogram[i];
            if (count >= target) return i / 255.0;
        }
        return 1.0;
    }

    private void LogTelemetry(string slug, string path)
    {
        var bridge = SimulationBridge.Instance;
        var vessel = bridge?.ActiveVessel;
        var universe = bridge?.Universe;
        if (vessel == null || universe == null) return;
        var body = universe.GetDominantBody(vessel.Position);
        if (body == null) return;

        double alt = vessel.GetAltitude(body);
        Vector3d surfVel = vessel.GetSurfaceVelocity(body);
        Vector3d up = (vessel.Position - body.Position).Normalized;
        double spd = surfVel.Magnitude;
        double vSpeed = surfVel.Dot(up);
        double q = vessel.GetDynamicPressure(body);
        double mass = System.Math.Max(vessel.TotalMass, 1.0);
        Vector3d nonGrav = (vessel.ComputeThrust(body) + vessel.ComputeDrag(body)) / mass;
        double g = nonGrav.Magnitude / 9.80665;
        string phase = MissionManager.Instance?.Phase.ToString() ?? "?";
        double maxT = vessel.Parts.Parts.Max(p => p.Temperature);
        double heatRatio = vessel.Parts.Parts.Max(p => p.ThermalRatio);
        double density = body.GetAtmosphericDensity(vessel.Position);
        double flux = ThermalModel.ComputeHeatFlux(density, spd);
        int selectedEngines = vessel.Parts.Parts
            .FirstOrDefault(p => p.Definition.Id == "starship_engines")?.SelectedEngineCount ?? 0;
        int contacts = vessel.LastSurfaceContact?.ContactCount ?? 0;
        double maxStroke = vessel.LastSurfaceContact?.Points.Max(p => p.PenetrationM) ?? 0.0;
        double peakLegLoad = vessel.LastSurfaceContact?.Points.Max(p => p.NormalLoadN) ?? 0.0;

        _log.WriteLine(
            $"CAPTURE {slug} path={path} alt={alt:F1} spd={spd:F1} vSpeed={vSpeed:F1} q={q:F0} g={g:F2} " +
            $"phase={phase} heatRatio={heatRatio:F3} maxT={maxT:F0} flux={flux:E2} " +
            $"omega={vessel.AngularVelocity.Magnitude:F4} selectedEngines={selectedEngines} " +
            $"contacts={contacts} maxStroke={maxStroke:F3} peakLegLoad={peakLegLoad:F0} " +
            $"settled={vessel.IsSurfaceSettled}");
        _log.Flush();
    }

    private static void DrainToReserve(Vessel vessel, double reserveFrac)
    {
        foreach (var p in vessel.Parts.Parts)
        {
            double cap = p.Definition.FuelCapacityLF + p.Definition.FuelCapacityOx;
            if (cap <= 0.0) continue;
            double target = cap * reserveFrac;
            double total = p.LiquidFuel + p.Oxidizer;
            if (total <= target) continue;
            double remove = total - target;
            double lfFrac = total > 1e-9 ? p.LiquidFuel / total : 0.45;
            p.LiquidFuel -= remove * lfFrac;
            p.Oxidizer -= remove * (1.0 - lfFrac);
        }
    }

    private static Quaterniond ShortestArc(Vector3d from, Vector3d to)
    {
        var f = from.Normalized;
        var t = to.Normalized;
        double dot = f.Dot(t);
        if (dot > 0.99999) return Quaterniond.Identity;
        if (dot < -0.99999)
        {
            Vector3d ax = System.Math.Abs(f.X) < 0.9 ? f.Cross(Vector3d.Right) : f.Cross(Vector3d.Up);
            return Quaterniond.FromAxisAngle(ax.Normalized, System.Math.PI);
        }
        Vector3d axis = f.Cross(t).Normalized;
        return Quaterniond.FromAxisAngle(axis, System.Math.Acos(System.Math.Clamp(dot, -1.0, 1.0)));
    }

    private void Finish(string reason)
    {
        if (_finished) return;
        _finished = true;
        _log.WriteLine($"SUMMARY reason={reason} frames={_frame}");
        _log.Flush();
        _log.Dispose();
        GD.Print($"[Playtest] finish: {reason}");
        GetTree().CallDeferred("quit");
    }

    public override void _ExitTree()
    {
        if (!_finished)
        {
            _log?.WriteLine("SUMMARY reason=ABORT");
            _log?.Flush();
            _log?.Dispose();
        }
    }
}
CS
}

verify_pngs() {
  local min_bytes="${1:-8000}"
  local found=0
  shopt -s nullglob
  for png in "$OUT_DIR"/exo_play_*.png; do
    found=1
    local size
    size="$(wc -c < "$png" | tr -d ' ')"
    if [[ "$size" -lt "$min_bytes" ]]; then
      echo "ERROR: PNG too small ($size bytes): $png" >&2
      return 1
    fi
  done
  shopt -u nullglob
  if [[ "$found" -eq 0 ]]; then
    echo "ERROR: no PNG captures in $OUT_DIR" >&2
    return 1
  fi

  if [[ "$MODE" == "full" ]]; then
    local required=(pad liftoff maxq orbit)
    for slug in "${required[@]}"; do
      if [[ ! -f "$OUT_DIR/exo_play_${slug}.png" ]]; then
        echo "ERROR: missing required milestone PNG: exo_play_${slug}.png" >&2
        return 1
      fi
    done
  elif [[ "$MODE" == "edl" ]]; then
    local required=(entry retro_burn flip_complete touchdown)
    for slug in "${required[@]}"; do
      if [[ ! -f "$OUT_DIR/exo_play_${slug}.png" ]]; then
        echo "ERROR: missing required EDL milestone PNG: exo_play_${slug}.png" >&2
        return 1
      fi
    done
    if ! grep -q 'SUMMARY reason=LANDED' "$LOG"; then
      echo "ERROR: deterministic EDL did not end in a verified landing" >&2
      return 1
    fi
    if ! grep -Eq 'CAPTURE touchdown .*contacts=[3-9][0-9]* .*settled=True' "$LOG"; then
      echo "ERROR: touchdown was not supported by at least three settled physical contacts" >&2
      return 1
    fi
  elif [[ "$MODE" == "atmosphere" ]]; then
    local required=(
      ground_day ground_sunrise ground_sunset ground_night
      10km_day 30km_day 70km_day 120km_day 400km_day
      10km_night 30km_night 70km_night 120km_night 400km_night
      cockpit_120km_day cockpit_120km_night
    )
    for slug in "${required[@]}"; do
      if [[ ! -f "$OUT_DIR/exo_play_${slug}.png" ]]; then
        echo "ERROR: missing atmosphere matrix PNG: exo_play_${slug}.png" >&2
        return 1
      fi
      if ! grep -q "^IMAGE slug=${slug} " "$LOG"; then
        echo "ERROR: missing image metrics for atmosphere case: ${slug}" >&2
        return 1
      fi
      if ! grep -q "^ATMOS_STATE slug=${slug} " "$LOG"; then
        echo "ERROR: missing physical state evidence for atmosphere case: ${slug}" >&2
        return 1
      fi
    done
    if ! grep -q 'SUMMARY reason=ATMOSPHERE_OK' "$LOG"; then
      echo "ERROR: atmosphere matrix did not finish cleanly" >&2
      return 1
    fi

    # Reject only objectively unusable captures here.  Perceptual thresholds belong in
    # review because a physically valid night frame can intentionally be very dark.
    if ! awk '
      /^IMAGE / {
        mean = clip = -1
        for (i = 1; i <= NF; i++) {
          if ($i ~ /^mean=/) { split($i, a, "="); mean = a[2] + 0 }
          if ($i ~ /^clippedFrac=/) { split($i, a, "="); clip = a[2] + 0 }
        }
        if (mean < 0.0005 || mean > 0.9995 || clip > 0.95) {
          print "ERROR: degenerate atmosphere capture: " $0 > "/dev/stderr"
          bad = 1
        }
      }
      END { exit bad }
    ' "$LOG"; then
      return 1
    fi
  fi

  echo "visual_playtest: verified PNG(s) in $OUT_DIR (min ${min_bytes} bytes)"
}

register_autoload
write_harness

if [[ "$SKIP_BUILD" -eq 0 ]]; then
  dotnet build ExosphereSimulation/ExosphereSimulation.csproj --nologo -v quiet
fi
dotnet build Exosphere.csproj --nologo -v quiet

mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR"/exo_play_*.png 2>/dev/null || true
: > "$LOG"

echo "visual_playtest: mode=$MODE out=$OUT_DIR log=$LOG"

xvfb-run -a -s "-screen 0 1920x1080x24" "$GODOT" \
  --path . --rendering-driver opengl3 \
  res://scenes/flight/Flight.tscn 2>&1 | tee -a "$LOG"

verify_pngs

if [[ "$MODE" == "smoke" ]]; then
  echo "visual_playtest: smoke OK"
elif [[ "$MODE" == "edl" ]]; then
  echo "visual_playtest: deterministic EDL verification OK"
elif [[ "$MODE" == "atmosphere" ]]; then
  echo "visual_playtest: atmosphere matrix OK — compare IMAGE/PERF rows in $LOG"
else
  echo "visual_playtest: full run complete — review $LOG for GAP lines"
fi
